//! Deterministic parser for PTCGL's "Copy to Clipboard" battle log text.
//!
//! The log turns out to be a very regular, line-oriented grammar: top-level
//! sentences like `"<Player> played <Card> to the Bench."`, indented `"- "`
//! sub-effects of the line above them, and `"   • "` bullet lists that are
//! themselves sub-detail of the `"- "` line above *them*. That regularity is
//! what makes a hand-written parser viable instead of the LLM-per-match
//! approach other PTCGL log parsers use — see `watcher/tests/fixtures/README.md`
//! for where the two sample logs this was built and tested against came from.
//!
//! Card-effect sub-detail (the `"- "`/`"   • "` lines — draws-within-abilities,
//! discards-within-item-effects, etc.) is open-ended: it grows with every new
//! card printed, so this doesn't attempt to model it structurally. Those lines
//! are kept verbatim as `TurnEvent::details` under the top-level event they
//! belong to. Only the top-level sentence shapes (which are stable — they're
//! generated by the game engine, not by card text) are parsed into
//! `EventKind` variants.

use std::sync::LazyLock;

use regex::Regex;

#[derive(Debug, Clone, PartialEq)]
pub struct BattleLog {
    /// The two players, in order of first appearance in the log.
    pub players: (String, String),
    pub setup: Setup,
    pub turns: Vec<Turn>,
    pub outcome: Outcome,
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct Setup {
    pub coin_flip: Option<CoinFlip>,
    /// Pre-turn-one events: opening hand draws, initial Active/Bench plays.
    pub events: Vec<TurnEvent>,
}

#[derive(Debug, Clone, PartialEq)]
pub struct CoinFlip {
    pub caller: String,
    pub called: String,
    pub winner: String,
    pub first_player: String,
}

#[derive(Debug, Clone, PartialEq)]
pub struct Turn {
    pub number: u32,
    pub player: String,
    pub events: Vec<TurnEvent>,
}

#[derive(Debug, Clone, PartialEq)]
pub struct TurnEvent {
    pub kind: EventKind,
    pub raw: String,
    /// Verbatim `"- "` sub-effect lines under this event (with any `"   • "`
    /// bullet list under a given one folded into that line as `": a, b, c"`).
    pub details: Vec<String>,
}

#[derive(Debug, Clone, PartialEq)]
pub enum EventKind {
    CoinFlipChose { player: String, called: String },
    CoinFlipWon { player: String },
    DecidedFirst { player: String },
    /// `cards` is only ever populated for the uploading player — PTCGL's log
    /// only reveals hand contents for the account that captured it, which is
    /// exactly the signal `BattleLog::perspective_player` uses.
    DrewOpeningHand { player: String, size: u32 },
    Drew { player: String, card: Option<String> },
    Played { player: String, card: String, location: Option<String> },
    AbilityUsed { player: String, pokemon: String, ability: String },
    Attack { player: String, pokemon: String, move_name: String, target_player: Option<String>, target_pokemon: Option<String>, damage: Option<u32> },
    Attached { player: String, card: String, target: String },
    Retreated { player: String, pokemon: String },
    Evolved { player: String, from: String, to: String },
    NowActive { player: String, pokemon: String },
    KnockedOut { player: String, pokemon: String },
    /// A card leaving play as a side effect (e.g. energy discarded on
    /// retreat, or a stage discarded when its evolution is knocked out) —
    /// distinct from a `"- "` detail's `"X discarded N cards."`, which is
    /// the *acting* player choosing to discard, not this.
    DiscardedFrom { card: String, player: String, pokemon: String },
    PrizeTaken { player: String, count: u32 },
    HandGain { player: String, card: Option<String> },
    EndedTurn { player: String },
    /// A Stadium/passive-item effect firing (e.g. "Battle Cage was
    /// activated."). No acting player — it's not either side's action.
    EffectActivated { source: String },
    Other,
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct Outcome {
    pub winner: Option<String>,
    pub raw: Option<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MatchResult {
    Win,
    Loss,
    Unknown,
}

impl BattleLog {
    /// The player whose hand contents (opening hand, and named single-card
    /// draws) appear in the log — i.e. whoever's account captured it. `None`
    /// if neither player's hand was ever revealed (shouldn't happen on a real
    /// capture, but the log format doesn't guarantee it).
    pub fn perspective_player(&self) -> Option<&str> {
        let reveals_hand = |player: &str| {
            let mut events = self.setup.events.iter().chain(self.turns.iter().flat_map(|t| &t.events));
            events.any(|e| match &e.kind {
                // A bullet list under the opening-hand draw (folded into a
                // detail as `": card, card, ..."` by `append_bullet_list`)
                // means real card names were shown — an empty-but-present
                // `"- N drawn cards."` detail with no list means they weren't.
                EventKind::DrewOpeningHand { player: p, .. } if p == player => {
                    e.details.iter().any(|d| d.contains(':'))
                }
                EventKind::Drew { player: p, card: Some(_) } if p == player => true,
                _ => false,
            })
        };
        if reveals_hand(&self.players.0) {
            Some(&self.players.0)
        } else if reveals_hand(&self.players.1) {
            Some(&self.players.1)
        } else {
            None
        }
    }

    pub fn result_for(&self, player: &str) -> MatchResult {
        match &self.outcome.winner {
            Some(winner) if winner == player => MatchResult::Win,
            Some(_) => MatchResult::Loss,
            None => MatchResult::Unknown,
        }
    }
}

pub fn parse(raw_text: &str) -> BattleLog {
    let mut players = PlayerOrder::default();
    let mut setup_events: Vec<TurnEvent> = Vec::new();
    let mut turns: Vec<Turn> = Vec::new();
    let mut current_turn: Option<Turn> = None;
    let mut outcome = Outcome::default();
    // Real captures have been seen both with an explicit "Turn # N - "
    // prefix and without one — when it's missing, number rounds by pairs of
    // headers (each round is one turn per player, in order), matching the
    // numbering the explicit form uses.
    let mut headers_seen: u32 = 0;

    for line in raw_text.lines() {
        let line = line.trim_end();
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed == "Setup" {
            continue;
        }

        if let Some((number, player)) = match_turn_header(trimmed) {
            if let Some(turn) = current_turn.take() {
                turns.push(turn);
            }
            let number = number.unwrap_or(headers_seen / 2 + 1);
            headers_seen += 1;
            players.seen(&player);
            current_turn = Some(Turn { number, player, events: Vec::new() });
            continue;
        }

        let events = match current_turn.as_mut() {
            Some(turn) => &mut turn.events,
            None => &mut setup_events,
        };

        if let Some(rest) = trimmed.strip_prefix("• ").or_else(|| trimmed.strip_prefix("- •")) {
            // Defensive: shouldn't hit given the indent-based check below,
            // kept only so a stray bullet never falls through to `Other`.
            append_bullet_list(events, rest);
            continue;
        }
        if line.starts_with("   ") && trimmed.starts_with('•') {
            let rest = trimmed.trim_start_matches('•').trim();
            append_bullet_list(events, rest);
            continue;
        }
        if let Some(rest) = trimmed.strip_prefix("- ") {
            append_detail(events, rest);
            continue;
        }

        if let Some(winner) = match_outcome(trimmed) {
            outcome = Outcome { winner: Some(winner), raw: Some(trimmed.to_string()) };
            continue;
        }

        let kind = classify_top_level(trimmed);
        if let Some(player) = kind.player() {
            players.seen(player);
        }
        events.push(TurnEvent { kind, raw: trimmed.to_string(), details: Vec::new() });
    }
    if let Some(turn) = current_turn.take() {
        turns.push(turn);
    }

    let coin_flip = build_coin_flip(&setup_events);

    BattleLog {
        players: players.into_pair(),
        setup: Setup { coin_flip, events: setup_events },
        turns,
        outcome,
    }
}

fn append_detail(events: &mut Vec<TurnEvent>, detail: &str) {
    match events.last_mut() {
        Some(event) => event.details.push(detail.to_string()),
        // A detail line with no preceding top-level event in this
        // turn/setup block — shouldn't happen on a well-formed log, but
        // keep it rather than silently dropping information.
        None => events.push(TurnEvent { kind: EventKind::Other, raw: format!("- {detail}"), details: Vec::new() }),
    }
}

fn append_bullet_list(events: &mut [TurnEvent], list: &str) {
    if let Some(event) = events.last_mut()
        && let Some(last_detail) = event.details.last_mut()
    {
        last_detail.push_str(": ");
        last_detail.push_str(list);
        return;
    }
    if let Some(event) = events.last_mut() {
        event.details.push(list.to_string());
    }
}

#[derive(Default)]
struct PlayerOrder(Vec<String>);

impl PlayerOrder {
    fn seen(&mut self, name: &str) {
        if !self.0.iter().any(|p| p == name) {
            self.0.push(name.to_string());
        }
    }

    fn into_pair(self) -> (String, String) {
        let mut it = self.0.into_iter();
        let a = it.next().unwrap_or_default();
        let b = it.next().unwrap_or_default();
        (a, b)
    }
}

impl EventKind {
    fn player(&self) -> Option<&str> {
        match self {
            EventKind::CoinFlipChose { player, .. }
            | EventKind::CoinFlipWon { player }
            | EventKind::DecidedFirst { player }
            | EventKind::DrewOpeningHand { player, .. }
            | EventKind::Drew { player, .. }
            | EventKind::Played { player, .. }
            | EventKind::AbilityUsed { player, .. }
            | EventKind::Attack { player, .. }
            | EventKind::Attached { player, .. }
            | EventKind::Retreated { player, .. }
            | EventKind::Evolved { player, .. }
            | EventKind::NowActive { player, .. }
            | EventKind::KnockedOut { player, .. }
            | EventKind::DiscardedFrom { player, .. }
            | EventKind::PrizeTaken { player, .. }
            | EventKind::HandGain { player, .. }
            | EventKind::EndedTurn { player } => Some(player),
            EventKind::EffectActivated { .. } | EventKind::Other => None,
        }
    }
}

// Possessive apostrophe: PTCGL's log inconsistently uses a straight `'` or a
// curly `’` (observed both in the same file), so every pattern below that
// needs one matches either via an inline `['\u{2019}]` character class.

macro_rules! re {
    ($name:ident, $pattern:expr) => {
        static $name: LazyLock<Regex> = LazyLock::new(|| Regex::new($pattern).unwrap());
    };
}

// The "Turn # N - " prefix has been observed present in some captures and
// absent in others (real capture: bare "<Player>'s Turn"), so it's optional.
re!(TURN_HEADER, r"^(?:Turn # (\d+) - )?(.+)'s Turn$");
// Player names don't contain spaces, so the token right after a sentence
// boundary (line start, or ". ") immediately before " wins." is the winner —
// avoids a naive `.+ wins\.$` swallowing the rest of a leading sentence like
// "All Prize cards taken. ".
re!(OUTCOME, r"(?:^|\.\s)(\S+) wins\.$");
re!(COIN_CHOSE, r"^(.+) chose (heads|tails) for the opening coin flip\.$");
re!(COIN_WON, r"^(.+) won the coin toss\.$");
re!(DECIDED_FIRST, r"^(.+) decided to go first\.$");
re!(DREW_OPENING, r"^(.+) drew (\d+) cards for the opening hand\.$");
re!(DREW_A_CARD, r"^(.+) drew a card\.$");
re!(DREW_NAMED, r"^(.+) drew (.+)\.$");
re!(PLAYED_LOCATION, r"^(.+) played (.+) to the (Active Spot|Bench|Stadium spot)\.$");
re!(PLAYED_PLAIN, r"^(.+) played (.+)\.$");
re!(ATTACK, r"^(.+)['\u{2019}]s (.+) used (.+) on (.+)['\u{2019}]s (.+) for (\d+) damage\.");
re!(ABILITY, r"^(.+)['\u{2019}]s (.+) used (.+)\.$");
re!(ATTACHED, r"^(.+) attached (.+) to (.+) (?:in the Active Spot|on the Bench)\.$");
re!(RETREATED, r"^(.+) retreated (.+) to the Bench\.$");
re!(EVOLVED, r"^(.+) evolved (.+) to (.+) (?:on the Bench|in the Active Spot)\.$");
re!(NOW_ACTIVE, r"^(.+)['\u{2019}]s (.+) is now in the Active Spot\.$");
re!(KNOCKED_OUT, r"^(.+)['\u{2019}]s (.+) was Knocked Out!$");
re!(DISCARDED_FROM, r"^(.+) was discarded from (.+)['\u{2019}]s (.+)\.$");
re!(PRIZE_TAKEN, r"^(.+) took (?:a Prize card|(\d+) Prize cards)\.$");
re!(HAND_GAIN, r"^(.+) was added to (.+)['\u{2019}]s hand\.$");
re!(ENDED_TURN, r"^(.+) ended their turn\.$");
re!(EFFECT_ACTIVATED, r"^(.+) was activated\.$");

fn match_turn_header(line: &str) -> Option<(Option<u32>, String)> {
    let caps = TURN_HEADER.captures(line)?;
    let number = caps.get(1).and_then(|m| m.as_str().parse().ok());
    Some((number, caps[2].to_string()))
}

fn match_outcome(line: &str) -> Option<String> {
    OUTCOME.captures(line).map(|c| c.get(1).unwrap().as_str().to_string())
}

fn classify_top_level(line: &str) -> EventKind {
    if let Some(c) = COIN_CHOSE.captures(line) {
        return EventKind::CoinFlipChose { player: c[1].to_string(), called: c[2].to_string() };
    }
    if let Some(c) = COIN_WON.captures(line) {
        return EventKind::CoinFlipWon { player: c[1].to_string() };
    }
    if let Some(c) = DECIDED_FIRST.captures(line) {
        return EventKind::DecidedFirst { player: c[1].to_string() };
    }
    if let Some(c) = DREW_OPENING.captures(line) {
        return EventKind::DrewOpeningHand { player: c[1].to_string(), size: c[2].parse().unwrap_or(0) };
    }
    if let Some(c) = DREW_A_CARD.captures(line) {
        return EventKind::Drew { player: c[1].to_string(), card: None };
    }
    if let Some(c) = ATTACK.captures(line) {
        return EventKind::Attack {
            player: c[1].to_string(),
            pokemon: c[2].to_string(),
            move_name: c[3].to_string(),
            target_player: Some(c[4].to_string()),
            target_pokemon: Some(c[5].to_string()),
            damage: c[6].parse().ok(),
        };
    }
    if let Some(c) = ABILITY.captures(line) {
        return EventKind::AbilityUsed { player: c[1].to_string(), pokemon: c[2].to_string(), ability: c[3].to_string() };
    }
    if let Some(c) = ATTACHED.captures(line) {
        return EventKind::Attached { player: c[1].to_string(), card: c[2].to_string(), target: c[3].to_string() };
    }
    if let Some(c) = RETREATED.captures(line) {
        return EventKind::Retreated { player: c[1].to_string(), pokemon: c[2].to_string() };
    }
    if let Some(c) = EVOLVED.captures(line) {
        return EventKind::Evolved { player: c[1].to_string(), from: c[2].to_string(), to: c[3].to_string() };
    }
    if let Some(c) = NOW_ACTIVE.captures(line) {
        return EventKind::NowActive { player: c[1].to_string(), pokemon: c[2].to_string() };
    }
    if let Some(c) = KNOCKED_OUT.captures(line) {
        return EventKind::KnockedOut { player: c[1].to_string(), pokemon: c[2].to_string() };
    }
    if let Some(c) = DISCARDED_FROM.captures(line) {
        return EventKind::DiscardedFrom { card: c[1].to_string(), player: c[2].to_string(), pokemon: c[3].to_string() };
    }
    if let Some(c) = PRIZE_TAKEN.captures(line) {
        let count = c.get(2).and_then(|m| m.as_str().parse().ok()).unwrap_or(1);
        return EventKind::PrizeTaken { player: c[1].to_string(), count };
    }
    if let Some(c) = HAND_GAIN.captures(line) {
        let card = &c[1];
        let card = if card == "A card" { None } else { Some(card.to_string()) };
        return EventKind::HandGain { player: c[2].to_string(), card };
    }
    if let Some(c) = ENDED_TURN.captures(line) {
        return EventKind::EndedTurn { player: c[1].to_string() };
    }
    if let Some(c) = EFFECT_ACTIVATED.captures(line) {
        return EventKind::EffectActivated { source: c[1].to_string() };
    }
    if let Some(c) = PLAYED_LOCATION.captures(line) {
        return EventKind::Played { player: c[1].to_string(), card: c[2].to_string(), location: Some(c[3].to_string()) };
    }
    if let Some(c) = PLAYED_PLAIN.captures(line) {
        return EventKind::Played { player: c[1].to_string(), card: c[2].to_string(), location: None };
    }
    // Tried last: "drew a card." and "drew N cards for the opening hand."
    // are both more specific shapes of "drew ...", so only a genuinely named
    // single-card draw (mid-turn, perspective player only) should fall
    // through to here.
    if let Some(c) = DREW_NAMED.captures(line) {
        return EventKind::Drew { player: c[1].to_string(), card: Some(c[2].to_string()) };
    }
    EventKind::Other
}

fn build_coin_flip(setup_events: &[TurnEvent]) -> Option<CoinFlip> {
    let mut caller = None;
    let mut called = None;
    let mut winner = None;
    let mut first_player = None;
    for event in setup_events {
        match &event.kind {
            EventKind::CoinFlipChose { player, called: c } => {
                caller = Some(player.clone());
                called = Some(c.clone());
            }
            EventKind::CoinFlipWon { player } => winner = Some(player.clone()),
            EventKind::DecidedFirst { player } => first_player = Some(player.clone()),
            _ => {}
        }
    }
    Some(CoinFlip { caller: caller?, called: called?, winner: winner?, first_player: first_player? })
}

#[cfg(test)]
mod tests {
    use super::*;

    const SHORT: &str = include_str!("../tests/fixtures/battle_short.txt");
    const FULL: &str = include_str!("../tests/fixtures/battle_full.txt");
    const REAL_NO_NUMBERS: &str = include_str!("../tests/fixtures/battle_real_no_turn_numbers.txt");

    #[test]
    fn parses_players_in_order_of_appearance() {
        let log = parse(SHORT);
        assert_eq!(log.players, ("Shinwrld".to_string(), "gklinsing".to_string()));
    }

    #[test]
    fn parses_coin_flip() {
        let log = parse(SHORT);
        let flip = log.setup.coin_flip.expect("coin flip");
        assert_eq!(flip.caller, "Shinwrld");
        assert_eq!(flip.called, "heads");
        assert_eq!(flip.winner, "Shinwrld");
        assert_eq!(flip.first_player, "Shinwrld");
    }

    #[test]
    fn identifies_perspective_player_from_revealed_hand() {
        // gklinsing's opening hand bullet-lists real card names; Shinwrld's
        // doesn't — gklinsing is whoever's account captured this log.
        let log = parse(SHORT);
        assert_eq!(log.perspective_player(), Some("gklinsing"));
    }

    #[test]
    fn parses_turn_structure() {
        let log = parse(SHORT);
        assert_eq!(log.turns.len(), 2);
        assert_eq!(log.turns[0].number, 1);
        assert_eq!(log.turns[0].player, "Shinwrld");
        assert_eq!(log.turns[1].player, "gklinsing");
    }

    #[test]
    fn parses_full_match_turn_count_and_outcome() {
        let log = parse(FULL);
        assert_eq!(log.turns.len(), 12); // 6 rounds x 2 players
        assert_eq!(log.outcome.winner.as_deref(), Some("gklinsing"));
        assert_eq!(log.result_for("gklinsing"), MatchResult::Win);
        assert_eq!(log.result_for("Shinwrld"), MatchResult::Loss);
    }

    #[test]
    fn parses_attack_with_damage() {
        let log = parse(FULL);
        let attack = log.turns.iter().flat_map(|t| &t.events).find(|e| {
            matches!(&e.kind, EventKind::Attack { pokemon, damage: Some(200), .. } if pokemon == "Mew ex")
        });
        assert!(attack.is_some(), "expected to find Mew ex's 200-damage attack");
    }

    #[test]
    fn parses_knockouts_and_prizes() {
        let log = parse(FULL);
        let all_events = log.turns.iter().flat_map(|t| &t.events);
        let ko_count = all_events.clone().filter(|e| matches!(e.kind, EventKind::KnockedOut { .. })).count();
        assert_eq!(ko_count, 7); // includes the turn-5 double-knockout
        let two_prize_turns = all_events
            .filter(|e| matches!(e.kind, EventKind::PrizeTaken { count: 2, .. }))
            .count();
        assert_eq!(two_prize_turns, 2); // both double-KO prize grabs in turn 6
    }

    #[test]
    fn attaches_nested_detail_lines_to_their_parent_event() {
        let log = parse(SHORT);
        // "gklinsing played Ultra Ball." in turn 1 has two "- " detail lines,
        // the first of which folds in a "   • " bullet list.
        let ultra_ball = log.turns[1]
            .events
            .iter()
            .find(|e| matches!(&e.kind, EventKind::Played { card, .. } if card == "Ultra Ball"))
            .expect("Ultra Ball play event");
        assert_eq!(
            ultra_ball.details,
            vec![
                "gklinsing discarded 2 cards.: Bravery Charm, Basic Lightning Energy",
                "gklinsing drew Miraidon ex.",
                "gklinsing shuffled their deck.",
            ]
        );
    }

    #[test]
    fn numbers_turns_by_pairs_when_the_log_omits_turn_numbers() {
        // A real capture (this fixture) turned out to omit the "Turn # N - "
        // prefix entirely, unlike the two reference-repo samples above —
        // turn numbers have to be inferred by counting header pairs instead.
        let log = parse(REAL_NO_NUMBERS);
        assert_eq!(log.turns.len(), 10); // 5 rounds x 2 players
        assert_eq!(log.turns[0].number, 1);
        assert_eq!(log.turns[1].number, 1);
        assert_eq!(log.turns[8].number, 5);
        assert_eq!(log.turns[9].number, 5);
    }

    #[test]
    fn parses_real_capture_outcome_and_perspective() {
        let log = parse(REAL_NO_NUMBERS);
        assert_eq!(log.players, ("Guibattis28".to_string(), "reindoe12".to_string()));
        assert_eq!(log.perspective_player(), Some("reindoe12"));
        assert_eq!(log.outcome.winner.as_deref(), Some("reindoe12"));
        assert_eq!(log.result_for("reindoe12"), MatchResult::Win);
        assert_eq!(log.result_for("Guibattis28"), MatchResult::Loss);
    }

    #[test]
    fn parses_stadium_effect_activation() {
        let log = parse(REAL_NO_NUMBERS);
        let activations = log
            .turns
            .iter()
            .flat_map(|t| &t.events)
            .filter(|e| matches!(&e.kind, EventKind::EffectActivated { source } if source == "Battle Cage"))
            .count();
        assert_eq!(activations, 4);
    }

    #[test]
    fn every_top_level_line_is_classified() {
        // Excludes FULL: it has one genuinely rare rule-notice line ("...can
        // no longer use VSTAR Powers.") that's an intentional gap per this
        // module's doc comment, not a regression to guard against.
        for fixture in [SHORT, REAL_NO_NUMBERS] {
            let log = parse(fixture);
            let unclassified: Vec<&str> = log
                .setup
                .events
                .iter()
                .chain(log.turns.iter().flat_map(|t| &t.events))
                .filter(|e| matches!(e.kind, EventKind::Other))
                .map(|e| e.raw.as_str())
                .collect();
            assert!(unclassified.is_empty(), "unclassified lines: {unclassified:?}");
        }
    }
}
